export type DoomEvent = {
  order: string; year: string; title: string; format: "PELÍCULA" | "SERIE"; duration: string;
  chapter: string; summary: string; key: string; status: "IMPRESCINDIBLE" | "AMPLÍA" | "DESTINO";
  image: string; events: string[]; characters: { name: string; id?: string; role: string }[]; connection: string;
};

export const doomEvents: DoomEvent[] = [
  { order: "01", year: "2019", title: "Avengers: Endgame", format: "PELÍCULA", duration: "3 h 01 min", chapter: "EL TIEMPO SE PUEDE ROMPER", summary: "El punto de partida: los Vengadores convierten el viaje temporal en una herramienta y dejan un equipo fragmentado.", key: "Viaje temporal · Legado · Nuevos Vengadores", status: "IMPRESCINDIBLE", image: "https://i.ytimg.com/vi/TcMBFSGVi1c/maxresdefault.jpg", events: ["Los Vengadores recuperan las Gemas desde distintos momentos del pasado.", "La muerte de Tony Stark y la retirada de Steve Rogers cierran la formación original.", "Loki escapa con el Teseracto y crea una ramificación temporal."], characters: [{ name: "Tony Stark", id: "iron", role: "El sacrificio que define el legado" }, { name: "Loki", role: "La variante que abre otra historia" }], connection: "Explica por qué el MCU llega a la siguiente crisis sin sus dos líderes originales y cómo nace la variante de Loki." },
  { order: "02", year: "2021–2023", title: "Loki · Temporadas 1 y 2", format: "SERIE", duration: "12 episodios", chapter: "NACE EL MULTIVERSO", summary: "La guía central para comprender variantes, líneas temporales, la TVA y la nueva estructura del multiverso.", key: "TVA · Variantes · Ramificaciones", status: "IMPRESCINDIBLE", image: "https://i.ytimg.com/vi/nW948Va-l10/maxresdefault.jpg", events: ["La TVA detiene a la variante de Loki creada en Endgame.", "La Línea Temporal Sagrada se ramifica tras la muerte de He Who Remains.", "Loki sostiene las líneas temporales y permite que el multiverso sobreviva."], characters: [{ name: "Loki", role: "Guardián de las historias" }, { name: "Mobius", role: "Agente y conciencia de la TVA" }], connection: "Es la pieza que mejor explica el vocabulario y las reglas que hacen posible una colisión entre realidades." },
  { order: "03", year: "2021", title: "Spider-Man: No Way Home", format: "PELÍCULA", duration: "2 h 28 min", chapter: "LAS REALIDADES SE TOCAN", summary: "Demuestra que personas de universos diferentes pueden coincidir y alterar una misma realidad.", key: "Hechizo · Visitantes · Memoria", status: "AMPLÍA", image: "https://i.ytimg.com/vi/JfVOs4VSpmA/maxresdefault.jpg", events: ["Un hechizo de Strange abre el paso a visitantes de otras realidades.", "Tres versiones de Spider-Man colaboran en el mismo universo.", "Peter sacrifica su identidad para cerrar la fractura."], characters: [{ name: "Peter Parker", id: "spider", role: "El detonante humano" }, { name: "Doctor Strange", id: "strange", role: "El guardián de la frontera" }], connection: "Convierte el multiverso en una experiencia física: otros universos ya no son teoría, pueden cruzar la puerta." },
  { order: "04", year: "2022", title: "Doctor Strange in the Multiverse of Madness", format: "PELÍCULA", duration: "2 h 06 min", chapter: "APARECEN LAS INCURSIONES", summary: "Introduce el concepto más importante de la ruta: dos universos pueden colisionar y destruirse.", key: "Incursiones · Darkhold · América Chávez", status: "IMPRESCINDIBLE", image: "https://i.ytimg.com/vi/aWzlQ2N6qqg/maxresdefault.jpg", events: ["América Chávez puede abrir portales entre universos.", "Wanda persigue otras versiones de su familia mediante el Darkhold.", "Clea advierte a Strange de que ha provocado una incursión."], characters: [{ name: "Stephen Strange", id: "strange", role: "Causante de una incursión" }, { name: "Wanda Maximoff", id: "wanda", role: "Poder capaz de atravesar realidades" }], connection: "Nombra directamente el peligro que puede convertir el multiverso en el campo de batalla de Doomsday." },
  { order: "05", year: "2024", title: "Deadpool & Wolverine", format: "PELÍCULA", duration: "2 h 08 min", chapter: "UN UNIVERSO PUEDE MORIR", summary: "Amplía el papel de la TVA, el Vacío y el deterioro de una línea temporal completa.", key: "TVA · Vacío · Ser ancla", status: "AMPLÍA", image: "https://i.ytimg.com/vi/73_1biulkYk/maxresdefault.jpg", events: ["La TVA supervisa universos más allá de una única línea temporal.", "El Vacío reúne restos y personajes de realidades eliminadas.", "La ausencia de un ser ancla puede condenar lentamente su mundo."], characters: [{ name: "Wade Wilson", role: "Visitante entre universos" }, { name: "Logan", role: "Una variante convertida en ancla" }], connection: "Prepara la convergencia con personajes procedentes del legado cinematográfico de los X-Men." },
  { order: "06", year: "2025", title: "The Fantastic Four: First Steps", format: "PELÍCULA", duration: "2 h 05 min", chapter: "LA PRIMERA FAMILIA", summary: "Presenta a Reed, Sue, Johnny y Ben en su propio universo antes de su regreso confirmado en Doomsday.", key: "Fantastic Four · Otro universo · Familia", status: "IMPRESCINDIBLE", image: "https://i.ytimg.com/vi/18QQWa5MEcs/maxresdefault.jpg", events: ["Los Cuatro Fantásticos protegen una Tierra retrofuturista distinta a la principal.", "Reed aborda amenazas cósmicas desde la ciencia y la responsabilidad familiar.", "La familia queda situada como pieza directa de la siguiente reunión de los Vengadores."], characters: [{ name: "Reed Richards", role: "La mente científica clave" }, { name: "Sue Storm", role: "El centro de la familia" }], connection: "Es la presentación MCU del equipo cuya participación en Avengers: Doomsday está confirmada oficialmente." },
  { order: "07", year: "2026", title: "Avengers: Doomsday", format: "PELÍCULA", duration: "18 diciembre", chapter: "EL DESTINO", summary: "Los Vengadores, los X-Men y los Cuatro Fantásticos convergen ante Victor von Doom.", key: "Doom · Convergencia · Realidades", status: "DESTINO", image: "https://i.ytimg.com/vi/399Ez7WHK5s/maxresdefault.jpg", events: ["Marvel Studios mantiene los detalles centrales de la trama en secreto.", "Victor von Doom está interpretado por Robert Downey Jr.", "La película se estrena el 18 de diciembre de 2026."], characters: [{ name: "Victor von Doom", role: "La amenaza confirmada" }, { name: "Reed Richards", role: "Su contrapunto intelectual" }], connection: "Todo lo demás es contexto; aquí convergen las líneas narrativas. Los elementos no anunciados deben tratarse como teoría." }
];
