export type MCUType = "PELÍCULA" | "SERIE" | "ESPECIAL" | "ONE-SHOT";
export type MCUContinuity = "SAGA PRINCIPAL" | "MARVEL TELEVISION" | "MULTIVERSO";
import { createContentSlug } from "@/lib/contentSlug";

export type MCUEntry = { slug: string; order: number; title: string; period: string; type: MCUType; continuity: MCUContinuity; phase: string; event: string };

const entries: Omit<MCUEntry, "order" | "slug">[] = [
  { title: "Eyes of Wakanda", period: "1260 a. C.–1896", type: "SERIE", continuity: "SAGA PRINCIPAL", phase: "EL PASADO", event: "Los Hatut Zeraze recuperan artefactos de vibranium a lo largo de la historia." },
  { title: "Capitán América: El Primer Vengador", period: "1943–1945", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "EL PASADO", event: "Steve Rogers se convierte en el primer Vengador y combate a HYDRA." },
  { title: "Agent Carter · Temporada 1", period: "1946", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "EL PASADO", event: "Peggy Carter afronta una conspiración mientras ayuda a Howard Stark." },
  { title: "Agent Carter · Temporada 2", period: "1947", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "EL PASADO", event: "Peggy investiga la materia cero y una trama en Los Ángeles." },
  { title: "Agent Carter", period: "1947", type: "ONE-SHOT", continuity: "SAGA PRINCIPAL", phase: "EL PASADO", event: "Peggy completa una misión que impulsa la creación de S.H.I.E.L.D." },
  { title: "Capitana Marvel", period: "1995", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "EL PASADO", event: "Carol Danvers descubre su origen y Nick Fury conoce la amenaza extraterrestre." },
  { title: "Iron Man", period: "2010", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 1", event: "Tony Stark construye su armadura y revela públicamente que es Iron Man." },
  { title: "Iron Man 2", period: "2011", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 1", event: "El legado de Stark atrae nuevos enemigos mientras Fury prepara la Iniciativa Vengadores." },
  { title: "El Increíble Hulk", period: "2011", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 1", event: "Bruce Banner busca controlar a Hulk mientras el ejército crea a Abominación." },
  { title: "El Consultor", period: "2011", type: "ONE-SHOT", continuity: "SAGA PRINCIPAL", phase: "FASE 1", event: "S.H.I.E.L.D. evita que Abominación sea incorporado a los Vengadores." },
  { title: "Algo divertido ocurrió de camino al martillo de Thor", period: "2011", type: "ONE-SHOT", continuity: "SAGA PRINCIPAL", phase: "FASE 1", event: "Phil Coulson demuestra sus capacidades antes de llegar a Nuevo México." },
  { title: "Thor", period: "2011", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 1", event: "Thor aprende humildad en la Tierra y Loki ocupa el trono de Asgard." },
  { title: "Los Vengadores", period: "2012", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 1", event: "Los héroes se unen contra Loki durante la batalla de Nueva York." },
  { title: "Artículo 47", period: "2012", type: "ONE-SHOT", continuity: "SAGA PRINCIPAL", phase: "FASE 1", event: "Una pareja encuentra un arma Chitauri tras la batalla de Nueva York." },
  { title: "Iron Man 3", period: "Navidad de 2012", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 2", event: "Tony afronta las secuelas emocionales de Nueva York y destruye sus armaduras." },
  { title: "Agents of S.H.I.E.L.D. · Temporada 1", period: "2013–2014", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "MARVEL TV", event: "El equipo de Coulson descubre que HYDRA lleva décadas infiltrada en S.H.I.E.L.D." },
  { title: "Todos aclaman al rey", period: "2013", type: "ONE-SHOT", continuity: "SAGA PRINCIPAL", phase: "FASE 2", event: "Trevor Slattery descubre que la organización de los Diez Anillos es real." },
  { title: "Thor: El Mundo Oscuro", period: "2013", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 2", event: "Thor combate a los Elfos Oscuros y el Éter revela ser una Gema del Infinito." },
  { title: "Capitán América: El Soldado de Invierno", period: "2014", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 2", event: "Steve descubre la infiltración de HYDRA y provoca la caída de S.H.I.E.L.D." },
  { title: "Guardianes de la Galaxia", period: "2014", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 2", event: "Un grupo de inadaptados protege Xandar de Ronan y la Gema del Poder." },
  { title: "Guardianes de la Galaxia Vol. 2", period: "2014", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 3", event: "Peter Quill conoce a Ego y el equipo consolida su familia elegida." },
  { title: "Daredevil · Temporada 1", period: "2015", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "DEFENDERS", event: "Matt Murdock se enfrenta a Wilson Fisk por el control de Hell's Kitchen." },
  { title: "Agents of S.H.I.E.L.D. · Temporada 2", period: "2014–2015", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "MARVEL TV", event: "Coulson reconstruye S.H.I.E.L.D. y descubre la existencia de los Inhumanos." },
  { title: "Vengadores: La Era de Ultrón", period: "2015", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 2", event: "Ultron destruye Sokovia; nacen Vision y la nueva formación de Vengadores." },
  { title: "Jessica Jones · Temporada 1", period: "2015", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "DEFENDERS", event: "Jessica afronta el control mental y el trauma causado por Kilgrave." },
  { title: "Ant-Man", period: "2015", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 2", event: "Scott Lang hereda el traje de Hank Pym y entra por primera vez en el Reino Cuántico." },
  { title: "Agents of S.H.I.E.L.D. · Temporada 3", period: "2015–2016", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "MARVEL TV", event: "El equipo protege a nuevos Inhumanos y combate a Hive." },
  { title: "Daredevil · Temporada 2", period: "2016", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "DEFENDERS", event: "Punisher y La Mano llevan al límite el código moral de Matt Murdock." },
  { title: "Capitán América: Civil War", period: "2016", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 3", event: "Los Acuerdos de Sokovia dividen a los Vengadores y presentan a Black Panther y Spider-Man." },
  { title: "Black Widow", period: "2016", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 4", event: "Natasha se reúne con su familia encubierta y derriba la Habitación Roja." },
  { title: "Black Panther", period: "2016", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 3", event: "T'Challa defiende el trono y decide abrir Wakanda al mundo." },
  { title: "Spider-Man: Homecoming", period: "2016", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 3", event: "Peter Parker aprende a ser héroe sin depender de la tecnología de Stark." },
  { title: "Luke Cage · Temporada 1", period: "2016", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "DEFENDERS", event: "Luke se convierte en el protector público de Harlem." },
  { title: "Iron Fist · Temporada 1", period: "2016", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "DEFENDERS", event: "Danny Rand regresa a Nueva York y combate la influencia de La Mano." },
  { title: "The Defenders", period: "2016", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "DEFENDERS", event: "Daredevil, Jessica Jones, Luke Cage e Iron Fist unen fuerzas contra La Mano." },
  { title: "The Punisher · Temporada 1", period: "2016", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "DEFENDERS", event: "Frank Castle descubre la conspiración detrás del asesinato de su familia." },
  { title: "Doctor Strange", period: "2016–2017", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 3", event: "Stephen Strange aprende las artes místicas y protege el continuo temporal." },
  { title: "Agents of S.H.I.E.L.D.: Slingshot", period: "2016", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "MARVEL TV", event: "Yo-Yo Rodríguez busca justicia durante la aplicación de los Acuerdos de Sokovia." },
  { title: "Agents of S.H.I.E.L.D. · Temporada 4", period: "2016–2017", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "MARVEL TV", event: "Ghost Rider, los LMD y Framework alteran al equipo de Coulson." },
  { title: "Inhumans", period: "2017", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "MARVEL TV", event: "La familia real Inhumana huye de Attilan tras el golpe de Maximus." },
  { title: "Jessica Jones · Temporadas 2 y 3", period: "2017", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "DEFENDERS", event: "Jessica investiga su origen y afronta la ruptura definitiva con Trish." },
  { title: "Luke Cage · Temporada 2", period: "2017", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "DEFENDERS", event: "Luke protege Harlem y termina ocupando el club de Harlem's Paradise." },
  { title: "Iron Fist · Temporada 2", period: "2017", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "DEFENDERS", event: "Danny intenta proteger Chinatown mientras Davos reclama el poder del Puño." },
  { title: "Daredevil · Temporada 3", period: "2017", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "DEFENDERS", event: "Fisk manipula al FBI y convierte a Dex en un falso Daredevil." },
  { title: "The Punisher · Temporada 2", period: "2017", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "DEFENDERS", event: "Frank protege a una joven mientras vuelve a enfrentarse a Billy Russo." },
  { title: "Runaways · Temporadas 1–3", period: "2017–2018", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "MARVEL TV", event: "Un grupo de adolescentes descubre que sus padres forman la organización PRIDE." },
  { title: "Cloak & Dagger · Temporadas 1 y 2", period: "2017–2018", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "MARVEL TV", event: "Tandy y Tyrone conectan sus poderes y protegen Nueva Orleans." },
  { title: "Thor: Ragnarok", period: "2017", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 3", event: "Asgard es destruido y sus supervivientes parten hacia la Tierra." },
  { title: "Agents of S.H.I.E.L.D. · Temporada 5", period: "2017–2091", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "MARVEL TV", event: "El equipo viaja a un futuro destruido y trata de romper un bucle temporal." },
  { title: "Ant-Man y la Avispa", period: "2018", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 3", event: "Janet regresa del Reino Cuántico mientras el chasquido deja atrapado a Scott." },
  { title: "Vengadores: Infinity War", period: "2018", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 3", event: "Thanos reúne las Gemas y elimina a la mitad de la vida del universo." },
  { title: "Agents of S.H.I.E.L.D. · Temporadas 6 y 7", period: "2019 / viaje temporal", type: "SERIE", continuity: "MARVEL TELEVISION", phase: "MARVEL TV", event: "El equipo combate a los Chronicoms y recorre el pasado de S.H.I.E.L.D." },
  { title: "Vengadores: Endgame", period: "2018–2023", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 3", event: "Los Vengadores revierten el Blip mediante un atraco temporal y derrotan a Thanos." },
  { title: "WandaVision", period: "2023", type: "SERIE", continuity: "SAGA PRINCIPAL", phase: "FASE 4", event: "El duelo de Wanda crea el Hex de Westview y despierta a la Bruja Escarlata." },
  { title: "Loki · Temporadas 1 y 2", period: "Fuera del tiempo", type: "SERIE", continuity: "MULTIVERSO", phase: "SAGA DEL MULTIVERSO", event: "Una variante de Loki descubre la TVA y termina sosteniendo las líneas del multiverso." },
  { title: "Shang-Chi y la leyenda de los Diez Anillos", period: "2024", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 4", event: "Shang-Chi hereda los Diez Anillos tras enfrentarse a su padre." },
  { title: "Falcon y el Soldado de Invierno", period: "2024", type: "SERIE", continuity: "SAGA PRINCIPAL", phase: "FASE 4", event: "Sam Wilson acepta el escudo y se convierte en el nuevo Capitán América." },
  { title: "Spider-Man: Lejos de casa", period: "2024", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 3", event: "Mysterio manipula a Peter y revela su identidad al mundo." },
  { title: "Spider-Man: No Way Home", period: "2024", type: "PELÍCULA", continuity: "MULTIVERSO", phase: "FASE 4", event: "Un hechizo atrae visitantes de otros universos y el mundo olvida a Peter Parker." },
  { title: "Eternals", period: "2024", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 4", event: "Los Eternos impiden el nacimiento de Tiamut y desafían a los Celestiales." },
  { title: "Doctor Strange en el Multiverso de la Locura", period: "2024", type: "PELÍCULA", continuity: "MULTIVERSO", phase: "FASE 4", event: "Strange y América Chávez atraviesan realidades; Clea anuncia una incursión." },
  { title: "Ojo de Halcón", period: "Navidad de 2024", type: "SERIE", continuity: "SAGA PRINCIPAL", phase: "FASE 4", event: "Clint Barton y Kate Bishop se enfrentan a la mafia deportiva y a Kingpin." },
  { title: "Echo", period: "2025", type: "SERIE", continuity: "SAGA PRINCIPAL", phase: "MARVEL SPOTLIGHT", event: "Maya López regresa a Oklahoma y rompe con la influencia de Wilson Fisk." },
  { title: "She-Hulk: Abogada Hulka", period: "2025", type: "SERIE", continuity: "SAGA PRINCIPAL", phase: "FASE 4", event: "Jennifer Walters equilibra su profesión legal con su identidad como She-Hulk." },
  { title: "Moon Knight", period: "2025", type: "SERIE", continuity: "SAGA PRINCIPAL", phase: "FASE 4", event: "Marc Spector y Steven Grant impiden que Ammit juzgue prematuramente a la humanidad." },
  { title: "Ms. Marvel", period: "2025", type: "SERIE", continuity: "SAGA PRINCIPAL", phase: "FASE 4", event: "Kamala Khan descubre el origen cósmico de su brazalete y sus poderes." },
  { title: "Thor: Love and Thunder", period: "2025", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 4", event: "Thor y Jane Foster detienen a Gorr; Thor adopta a Love." },
  { title: "Black Panther: Wakanda Forever", period: "2025", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 4", event: "Shuri asume el manto de Pantera Negra y alcanza la paz con Talokan." },
  { title: "Ironheart", period: "2025", type: "SERIE", continuity: "SAGA PRINCIPAL", phase: "FASE 5", event: "Riri Williams enfrenta su tecnología con la magia de Parker Robbins." },
  { title: "Invasión Secreta", period: "2025", type: "SERIE", continuity: "SAGA PRINCIPAL", phase: "FASE 5", event: "Nick Fury intenta detener una rebelión Skrull infiltrada en la Tierra." },
  { title: "Ant-Man y la Avispa: Quantumanía", period: "2025", type: "PELÍCULA", continuity: "MULTIVERSO", phase: "FASE 5", event: "La familia de Scott entra en el Reino Cuántico y combate a Kang el Conquistador." },
  { title: "Capitán América: Brave New World", period: "2026", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 5", event: "Sam Wilson afronta una conspiración global alrededor del adamantium." },
  { title: "Thunderbolts*", period: "2026", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 5", event: "Un equipo de antihéroes sobrevive a una trampa y emerge como los Nuevos Vengadores." },
  { title: "Guardianes de la Galaxia: Especial Felices Fiestas", period: "Navidad de 2025", type: "ESPECIAL", continuity: "SAGA PRINCIPAL", phase: "FASE 4", event: "Mantis y Drax viajan a la Tierra para devolverle la alegría a Peter." },
  { title: "Guardianes de la Galaxia Vol. 3", period: "2026", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 5", event: "Los Guardianes rescatan a Rocket y emprenden caminos nuevos." },
  { title: "Werewolf by Night", period: "Fecha indeterminada", type: "ESPECIAL", continuity: "SAGA PRINCIPAL", phase: "MARVEL STUDIOS SPECIAL", event: "Una cacería secreta presenta a Jack Russell, Elsa Bloodstone y Man-Thing." },
  { title: "Agatha, ¿quién si no?", period: "2026", type: "SERIE", continuity: "SAGA PRINCIPAL", phase: "FASE 5", event: "Agatha recorre la Senda de las Brujas y revela la identidad de Billy Maximoff." },
  { title: "The Marvels", period: "2026", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 5", event: "Carol, Monica y Kamala intercambian posiciones; una grieta conecta otra realidad." },
  { title: "Daredevil: Born Again · Temporada 1", period: "2027", type: "SERIE", continuity: "SAGA PRINCIPAL", phase: "MARVEL TELEVISION", event: "Matt Murdock se enfrenta al ascenso político de Wilson Fisk en Nueva York." },
  { title: "The Punisher: One Last Kill", period: "2027", type: "ESPECIAL", continuity: "SAGA PRINCIPAL", phase: "MARVEL TELEVISION", event: "Frank Castle regresa en un especial conectado con el nuevo ciclo de Daredevil." },
  { title: "Daredevil: Born Again · Temporada 2", period: "2027", type: "SERIE", continuity: "SAGA PRINCIPAL", phase: "MARVEL TELEVISION", event: "La lucha contra el régimen de Fisk continúa en Nueva York." },
  { title: "Deadpool y Lobezno", period: "2028 / fuera del tiempo", type: "PELÍCULA", continuity: "MULTIVERSO", phase: "FASE 5", event: "Deadpool entra en la TVA y salva su universo junto a una variante de Wolverine." },
  { title: "Los Cuatro Fantásticos: Primeros pasos", period: "Años 60 · Tierra-828", type: "PELÍCULA", continuity: "MULTIVERSO", phase: "FASE 6", event: "La Primera Familia protege su mundo retrofuturista frente a Galactus." },
  { title: "I Am Groot · Temporadas 1 y 2", period: "Entre Guardianes Vol. 1 y Vol. 2", type: "SERIE", continuity: "SAGA PRINCIPAL", phase: "MARVEL ANIMATION", event: "Baby Groot vive pequeñas aventuras durante sus primeros años con los Guardianes." },
  { title: "What If...? · Temporadas 1–3", period: "Multiverso", type: "SERIE", continuity: "MULTIVERSO", phase: "MARVEL ANIMATION", event: "El Vigilante observa realidades donde las decisiones del MCU tomaron otros caminos." },
  { title: "X-Men '97", period: "Universo alternativo · 1997", type: "SERIE", continuity: "MULTIVERSO", phase: "MARVEL ANIMATION", event: "Los X-Men continúan el sueño de Xavier mientras mutantes y humanos afrontan una nueva crisis." },
  { title: "Tu amigo y vecino Spider-Man", period: "Universo alternativo", type: "SERIE", continuity: "MULTIVERSO", phase: "MARVEL ANIMATION", event: "Otra realidad explora los primeros pasos de Peter Parker bajo la mentoría de Norman Osborn." },
  { title: "Marvel Zombies", period: "Universo alternativo", type: "SERIE", continuity: "MULTIVERSO", phase: "MARVEL ANIMATION", event: "Un grupo de supervivientes combate una plaga que convirtió a los héroes en zombis." },
  { title: "Wonder Man", period: "Cronología reciente", type: "SERIE", continuity: "SAGA PRINCIPAL", phase: "FASE 6", event: "Simon Williams intenta abrirse camino como actor dentro del Hollywood del MCU." },
  { title: "Spider-Man: Brand New Day", period: "2028", type: "PELÍCULA", continuity: "SAGA PRINCIPAL", phase: "FASE 6", event: "La siguiente historia de Peter Parker continúa después del sacrificio de su identidad." },
  { title: "Avengers: Doomsday", period: "Próximo destino", type: "PELÍCULA", continuity: "MULTIVERSO", phase: "FASE 6", event: "Victor von Doom reúne en una misma crisis a Vengadores, X-Men y Fantastic Four." }
];

export const mcuCatalog: MCUEntry[] = entries.map((entry, index) => ({
  ...entry,
  slug: createContentSlug(entry.title),
  order: index + 1,
}));
