import type { TitleDetails } from "./types";

export const marvelTelevisionTitleDetails: TitleDetails[] = [
  {
      titleId: "inhumans", spoilerFreeSynopsis: "Un golpe de Estado separa a la familia real Inhumana de Attilan y la obliga a sobrevivir en Hawái mientras intenta recuperar su hogar.", releaseDate: "29 SEP 2017", releaseDateISO: "2017-09-29", runtime: "8 EPISODIOS", certification: "TV-PG", status: "ESTRENADO", availability: "DISNEY+", directors: ["Roel Reiné", "Chris Fisher", "David Straiton"], writers: ["Scott Buck"], cast: ["Anson Mount", "Serinda Swan", "Ken Leung", "Eme Ikwuakor", "Isabelle Cornish", "Iwan Rheon"], trailerId: "1sYF1SXcWqQ", watchBefore: ["agents-of-s-h-i-e-l-d-temporada-3"], watchAfter: [], postCredits: [], sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/marvel-s-inhumans/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "agent-carter-temporada-1", spoilerFreeSynopsis: "En 1946, Peggy Carter compagina el trabajo administrativo en la SSR con misiones clandestinas para limpiar el nombre de Howard Stark.", releaseDate: "6 ENE 2015", releaseDateISO: "2015-01-06", runtime: "8 EPISODIOS", certification: "TV-PG", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Louis D'Esposito", "Joe Russo", "Scott Winant"], writers: ["Christopher Markus", "Stephen McFeely", "Michele Fazekas", "Tara Butters"], cast: ["Hayley Atwell", "James D'Arcy", "Chad Michael Murray", "Enver Gjokaj", "Shea Whigham"], trailerId: "", watchBefore: ["capitan-america-el-primer-vengador"], watchAfter: ["agent-carter-temporada-2"], postCredits: [], sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/marvel-s-agent-carter/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "agent-carter-temporada-2", spoilerFreeSynopsis: "Peggy viaja a Los Ángeles para investigar un asesinato imposible y descubre una conspiración alrededor de la misteriosa Materia Cero.", releaseDate: "19 ENE 2016", releaseDateISO: "2016-01-19", runtime: "10 EPISODIOS", certification: "TV-PG", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Jennifer Getzinger", "David Platt", "Metin Hüseyin"], writers: ["Michele Fazekas", "Tara Butters", "Chris Dingess"], cast: ["Hayley Atwell", "James D'Arcy", "Enver Gjokaj", "Wynn Everett", "Reggie Austin"], trailerId: "", watchBefore: ["agent-carter-temporada-1"], watchAfter: ["agent-carter"], postCredits: [], sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/marvel-s-agent-carter/2" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "agents-of-s-h-i-e-l-d-temporada-1", spoilerFreeSynopsis: "Phil Coulson reúne un equipo móvil para investigar personas y objetos extraordinarios mientras una conspiración crece dentro de S.H.I.E.L.D.", releaseDate: "24 SEP 2013", releaseDateISO: "2013-09-24", runtime: "22 EPISODIOS", certification: "TV-PG", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Joss Whedon", "David Straiton", "Vincent Misiano"], writers: ["Jed Whedon", "Maurissa Tancharoen", "Jeffrey Bell"], cast: ["Clark Gregg", "Ming-Na Wen", "Brett Dalton", "Chloe Bennet", "Iain De Caestecker", "Elizabeth Henstridge"], trailerId: "", watchBefore: ["los-vengadores", "iron-man-3"], watchAfter: ["capitan-america-el-soldado-de-invierno", "agents-of-s-h-i-e-l-d-temporada-2"], postCredits: [], sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/marvel-s-agents-of-s-h-i-e-l-d/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "agents-of-s-h-i-e-l-d-temporada-2", spoilerFreeSynopsis: "Tras la caída de S.H.I.E.L.D., Coulson reconstruye la organización desde la clandestinidad mientras el origen de Skye conduce hasta los Inhumanos.", releaseDate: "23 SEP 2014", releaseDateISO: "2014-09-23", runtime: "22 EPISODIOS", certification: "TV-PG", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Vincent Misiano", "Jesse Bochco", "Kevin Tancharoen"], writers: ["Jed Whedon", "Maurissa Tancharoen", "Jeffrey Bell"], cast: ["Clark Gregg", "Ming-Na Wen", "Chloe Bennet", "Iain De Caestecker", "Elizabeth Henstridge", "Nick Blood"], trailerId: "", watchBefore: ["agents-of-s-h-i-e-l-d-temporada-1"], watchAfter: ["vengadores-la-era-de-ultron", "agents-of-s-h-i-e-l-d-temporada-3"], postCredits: [], sources: [{ label: "MARVEL TELEVISION", url: "https://www.marvel.com/tv-shows" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "agents-of-s-h-i-e-l-d-temporada-3", spoilerFreeSynopsis: "El equipo busca y protege nuevos Inhumanos mientras HYDRA intenta traer a la Tierra a una antigua entidad conocida como Hive.", releaseDate: "29 SEP 2015", releaseDateISO: "2015-09-29", runtime: "22 EPISODIOS", certification: "TV-PG", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Vincent Misiano", "Kevin Tancharoen", "Jesse Bochco"], writers: ["Jed Whedon", "Maurissa Tancharoen", "Jeffrey Bell"], cast: ["Clark Gregg", "Ming-Na Wen", "Chloe Bennet", "Iain De Caestecker", "Elizabeth Henstridge", "Henry Simmons"], trailerId: "", watchBefore: ["agents-of-s-h-i-e-l-d-temporada-2"], watchAfter: ["agents-of-s-h-i-e-l-d-slingshot", "agents-of-s-h-i-e-l-d-temporada-4"], postCredits: [], sources: [{ label: "MARVEL TELEVISION", url: "https://www.marvel.com/tv-shows" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "agents-of-s-h-i-e-l-d-slingshot", spoilerFreeSynopsis: "Elena Rodríguez emprende una misión personal mientras espera la ratificación de los Acuerdos de Sokovia y recuerda su incorporación al equipo de Coulson.", releaseDate: "13 DIC 2016", releaseDateISO: "2016-12-13", runtime: "6 WEBISODIOS", certification: "TV-PG", status: "ESTRENADO", availability: "DIGITAL", directors: ["Joe Quesada"], writers: ["Geoffrey Colo"], cast: ["Natalia Cordova-Buckley", "Clark Gregg", "Ming-Na Wen", "Chloe Bennet", "Jason O'Mara"], trailerId: "", watchBefore: ["agents-of-s-h-i-e-l-d-temporada-3"], watchAfter: ["agents-of-s-h-i-e-l-d-temporada-4"], postCredits: [], sources: [{ label: "MARVEL TELEVISION", url: "https://www.marvel.com/tv-shows" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "agents-of-s-h-i-e-l-d-temporada-4", spoilerFreeSynopsis: "Ghost Rider, androides LMD y una realidad virtual llamada Framework obligan al equipo a combatir amenazas físicas, tecnológicas y digitales.", releaseDate: "20 SEP 2016", releaseDateISO: "2016-09-20", runtime: "22 EPISODIOS", certification: "TV-14", status: "ESTRENADO", availability: "DISNEY+", directors: ["Billy Gierhart", "Kevin Tancharoen", "Jesse Bochco"], writers: ["Jed Whedon", "Maurissa Tancharoen", "Jeffrey Bell"], cast: ["Clark Gregg", "Ming-Na Wen", "Chloe Bennet", "Iain De Caestecker", "Elizabeth Henstridge", "Gabriel Luna"], trailerId: "", watchBefore: ["agents-of-s-h-i-e-l-d-slingshot"], watchAfter: ["agents-of-s-h-i-e-l-d-temporada-5"], postCredits: [], sources: [{ label: "MARVEL TELEVISION", url: "https://www.marvel.com/tv-shows" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "agents-of-s-h-i-e-l-d-temporada-5", spoilerFreeSynopsis: "El equipo aparece en una estación espacial del futuro y descubre que debe regresar al presente para impedir la destrucción de la Tierra.", releaseDate: "1 DIC 2017", releaseDateISO: "2017-12-01", runtime: "22 EPISODIOS", certification: "TV-14", status: "ESTRENADO", availability: "DISNEY+", directors: ["Jesse Bochco", "Kevin Tancharoen", "Nina Lopez-Corrado"], writers: ["Jed Whedon", "Maurissa Tancharoen", "Jeffrey Bell"], cast: ["Clark Gregg", "Ming-Na Wen", "Chloe Bennet", "Iain De Caestecker", "Elizabeth Henstridge", "Henry Simmons"], trailerId: "", watchBefore: ["agents-of-s-h-i-e-l-d-temporada-4"], watchAfter: ["agents-of-s-h-i-e-l-d-temporadas-6-y-7"], postCredits: [], sources: [{ label: "MARVEL TELEVISION", url: "https://www.marvel.com/tv-shows" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "agents-of-s-h-i-e-l-d-temporadas-6-y-7", spoilerFreeSynopsis: "Los agentes afrontan una amenaza con el rostro de Coulson y una invasión Chronicom antes de recorrer la historia para preservar su línea temporal.", releaseDate: "2019–2020", releaseDateISO: "2019-05-10", runtime: "26 EPISODIOS", certification: "TV-14", status: "ESTRENADO", availability: "DISNEY+", directors: ["Clark Gregg", "Kevin Tancharoen", "Nina Lopez-Corrado"], writers: ["Jed Whedon", "Maurissa Tancharoen", "Jeffrey Bell"], cast: ["Clark Gregg", "Ming-Na Wen", "Chloe Bennet", "Elizabeth Henstridge", "Henry Simmons", "Natalia Cordova-Buckley"], trailerId: "", watchBefore: ["agents-of-s-h-i-e-l-d-temporada-5"], watchAfter: [], postCredits: [], sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/marvel-s-agents-of-s-h-i-e-l-d/7" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "daredevil-temporada-1", spoilerFreeSynopsis: "El abogado ciego Matt Murdock protege Hell's Kitchen de noche y descubre que el empresario Wilson Fisk controla la reconstrucción criminal del barrio.", releaseDate: "10 ABR 2015", releaseDateISO: "2015-04-10", runtime: "13 EPISODIOS", certification: "TV-MA", status: "ESTRENADO", availability: "DISNEY+", directors: ["Phil Abraham", "Adam Kane", "Farren Blackburn"], writers: ["Drew Goddard", "Steven S. DeKnight"], cast: ["Charlie Cox", "Deborah Ann Woll", "Elden Henson", "Rosario Dawson", "Vincent D'Onofrio"], trailerId: "", watchBefore: ["los-vengadores"], watchAfter: ["jessica-jones-temporada-1", "daredevil-temporada-2"], postCredits: [], sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/marvel-s-daredevil/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "daredevil-temporada-2", spoilerFreeSynopsis: "La llegada de Punisher y el regreso de Elektra obligan a Matt a cuestionar sus límites mientras La Mano extiende su guerra por Nueva York.", releaseDate: "18 MAR 2016", releaseDateISO: "2016-03-18", runtime: "13 EPISODIOS", certification: "TV-MA", status: "ESTRENADO", availability: "DISNEY+", directors: ["Phil Abraham", "Marc Jobst", "Floria Sigismondi"], writers: ["Doug Petrie", "Marco Ramirez"], cast: ["Charlie Cox", "Jon Bernthal", "Élodie Yung", "Deborah Ann Woll", "Elden Henson", "Vincent D'Onofrio"], trailerId: "", watchBefore: ["daredevil-temporada-1"], watchAfter: ["the-defenders", "the-punisher-temporada-1"], postCredits: [], sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/marvel-s-daredevil/2" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "daredevil-temporada-3", spoilerFreeSynopsis: "Tras sobrevivir a Midland Circle, Matt atraviesa una crisis de fe mientras Fisk manipula al FBI y utiliza a un agente capaz de imitar a Daredevil.", releaseDate: "19 OCT 2018", releaseDateISO: "2018-10-19", runtime: "13 EPISODIOS", certification: "TV-MA", status: "ESTRENADO", availability: "DISNEY+", directors: ["Marc Jobst", "Alex Garcia Lopez", "Jennifer Getzinger"], writers: ["Erik Oleson"], cast: ["Charlie Cox", "Deborah Ann Woll", "Elden Henson", "Vincent D'Onofrio", "Wilson Bethel", "Jay Ali"], trailerId: "", watchBefore: ["the-defenders"], watchAfter: ["ojo-de-halcon", "daredevil-born-again-temporada-1"], postCredits: [], sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/marvel-s-daredevil/3" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "jessica-jones-temporada-1", spoilerFreeSynopsis: "La detective Jessica Jones intenta reconstruir su vida hasta que Kilgrave, el hombre que controló y traumatizó su mente, regresa a Nueva York.", releaseDate: "20 NOV 2015", releaseDateISO: "2015-11-20", runtime: "13 EPISODIOS", certification: "TV-MA", status: "ESTRENADO", availability: "DISNEY+", directors: ["S. J. Clarkson", "David Petrarca", "Uta Briesewitz"], writers: ["Melissa Rosenberg"], cast: ["Krysten Ritter", "Mike Colter", "Rachael Taylor", "Wil Traval", "Carrie-Anne Moss", "David Tennant"], trailerId: "", watchBefore: ["daredevil-temporada-1"], watchAfter: ["luke-cage-temporada-1", "the-defenders"], postCredits: [], sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/marvel-s-jessica-jones/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "jessica-jones-temporadas-2-y-3", spoilerFreeSynopsis: "Jessica investiga el origen de sus poderes y después se enfrenta a un asesino que convierte su ruptura con Trish en una crisis irreversible.", releaseDate: "2018–2019", releaseDateISO: "2018-03-08", runtime: "26 EPISODIOS", certification: "TV-MA", status: "ESTRENADO", availability: "DISNEY+", directors: ["Anna Foerster", "Uta Briesewitz", "Jennifer Getzinger"], writers: ["Melissa Rosenberg"], cast: ["Krysten Ritter", "Rachael Taylor", "Eka Darville", "Carrie-Anne Moss", "Janet McTeer", "Benjamin Walker"], trailerId: "", watchBefore: ["the-defenders"], watchAfter: ["daredevil-born-again-temporada-2"], postCredits: [], sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/marvel-s-jessica-jones/3" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "luke-cage-temporada-1", spoilerFreeSynopsis: "Un experimento concede a Luke Cage piel indestructible y lo empuja a dejar el anonimato para proteger Harlem de Cottonmouth y su red criminal.", releaseDate: "30 SEP 2016", releaseDateISO: "2016-09-30", runtime: "13 EPISODIOS", certification: "TV-MA", status: "ESTRENADO", availability: "DISNEY+", directors: ["Paul McGuigan", "Clark Johnson", "Phil Abraham"], writers: ["Cheo Hodari Coker"], cast: ["Mike Colter", "Mahershala Ali", "Simone Missick", "Theo Rossi", "Alfre Woodard", "Rosario Dawson"], trailerId: "", watchBefore: ["jessica-jones-temporada-1"], watchAfter: ["the-defenders", "luke-cage-temporada-2"], postCredits: [], sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/marvel-s-luke-cage/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "luke-cage-temporada-2", spoilerFreeSynopsis: "Convertido en símbolo público de Harlem, Luke se enfrenta a Bushmaster y a la tentación de controlar el crimen para mantener la paz.", releaseDate: "22 JUN 2018", releaseDateISO: "2018-06-22", runtime: "13 EPISODIOS", certification: "TV-MA", status: "ESTRENADO", availability: "DISNEY+", directors: ["Lucy Liu", "Marc Jobst", "Clark Johnson"], writers: ["Cheo Hodari Coker"], cast: ["Mike Colter", "Simone Missick", "Theo Rossi", "Mustafa Shakir", "Gabrielle Dennis", "Alfre Woodard"], trailerId: "", watchBefore: ["the-defenders"], watchAfter: [], postCredits: [], sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/marvel-s-luke-cage/2" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "iron-fist-temporada-1", spoilerFreeSynopsis: "Danny Rand regresa a Nueva York tras quince años para recuperar su empresa y cumplir su deber como portador del Puño de Hierro frente a La Mano.", releaseDate: "17 MAR 2017", releaseDateISO: "2017-03-17", runtime: "13 EPISODIOS", certification: "TV-MA", status: "ESTRENADO", availability: "DISNEY+", directors: ["John Dahl", "Tom Shankland", "Uta Briesewitz"], writers: ["Scott Buck"], cast: ["Finn Jones", "Jessica Henwick", "Tom Pelphrey", "Jessica Stroup", "Sacha Dhawan", "Rosario Dawson"], trailerId: "", watchBefore: ["daredevil-temporada-2"], watchAfter: ["the-defenders", "iron-fist-temporada-2"], postCredits: [], sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/marvel-s-iron-fist/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "iron-fist-temporada-2", spoilerFreeSynopsis: "Danny protege Chinatown mientras Davos reclama el poder del Puño de Hierro y Colleen Wing descubre una conexión propia con su legado.", releaseDate: "7 SEP 2018", releaseDateISO: "2018-09-07", runtime: "10 EPISODIOS", certification: "TV-MA", status: "ESTRENADO", availability: "DISNEY+", directors: ["David Dobkin", "Rachel Talalay", "Sanford Bookstaver"], writers: ["M. Raven Metzner"], cast: ["Finn Jones", "Jessica Henwick", "Tom Pelphrey", "Jessica Stroup", "Sacha Dhawan", "Alice Eve"], trailerId: "", watchBefore: ["the-defenders", "luke-cage-temporada-2"], watchAfter: [], postCredits: [], sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/marvel-s-iron-fist/2" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "the-defenders", spoilerFreeSynopsis: "Daredevil, Jessica Jones, Luke Cage e Iron Fist convergen en una investigación que revela el plan de La Mano para destruir Nueva York.", releaseDate: "18 AGO 2017", releaseDateISO: "2017-08-18", runtime: "8 EPISODIOS", certification: "TV-MA", status: "ESTRENADO", availability: "DISNEY+", directors: ["S. J. Clarkson", "Peter Hoar", "Uta Briesewitz"], writers: ["Douglas Petrie", "Marco Ramirez"], cast: ["Charlie Cox", "Krysten Ritter", "Mike Colter", "Finn Jones", "Sigourney Weaver", "Élodie Yung"], trailerId: "", watchBefore: ["daredevil-temporada-2", "jessica-jones-temporada-1", "luke-cage-temporada-1", "iron-fist-temporada-1"], watchAfter: ["daredevil-temporada-3"], postCredits: [], sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/marvel-s-the-defenders/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "the-punisher-temporada-1", spoilerFreeSynopsis: "Frank Castle descubre que el asesinato de su familia forma parte de una conspiración militar y se alía con el analista David Lieberman para exponerla.", releaseDate: "17 NOV 2017", releaseDateISO: "2017-11-17", runtime: "13 EPISODIOS", certification: "TV-MA", status: "ESTRENADO", availability: "DISNEY+", directors: ["Tom Shankland", "Andy Goddard", "Marc Jobst"], writers: ["Steve Lightfoot"], cast: ["Jon Bernthal", "Ebon Moss-Bachrach", "Ben Barnes", "Amber Rose Revah", "Daniel Webber", "Deborah Ann Woll"], trailerId: "", watchBefore: ["daredevil-temporada-2"], watchAfter: ["the-punisher-temporada-2"], postCredits: [], sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/marvel-s-the-punisher/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "the-punisher-temporada-2", spoilerFreeSynopsis: "Frank intenta comenzar de nuevo, pero decide proteger a una joven perseguida mientras Billy Russo reaparece y reconstruye su identidad.", releaseDate: "18 ENE 2019", releaseDateISO: "2019-01-18", runtime: "13 EPISODIOS", certification: "TV-MA", status: "ESTRENADO", availability: "DISNEY+", directors: ["Jim O'Hanlon", "Iain B. MacDonald", "Alex Garcia Lopez"], writers: ["Steve Lightfoot"], cast: ["Jon Bernthal", "Ben Barnes", "Amber Rose Revah", "Josh Stewart", "Floriana Lima", "Giorgia Whigham"], trailerId: "", watchBefore: ["the-punisher-temporada-1"], watchAfter: ["daredevil-born-again-temporada-1", "the-punisher-one-last-kill"], postCredits: [], sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/marvel-s-the-punisher/2" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "runaways-temporadas-1-3", spoilerFreeSynopsis: "Seis adolescentes descubren que sus padres pertenecen a una organización criminal y huyen juntos mientras investigan el origen de sus propias habilidades.", releaseDate: "2017–2019", releaseDateISO: "2017-11-21", runtime: "33 EPISODIOS", certification: "TV-14", status: "ESTRENADO", availability: "DISPONIBILIDAD SEGÚN REGIÓN", directors: ["Roxann Dawson", "Jeffrey W. Byrd", "Jeremy Webb"], writers: ["Josh Schwartz", "Stephanie Savage"], cast: ["Rhenzy Feliz", "Lyrica Okano", "Virginia Gardner", "Ariela Barer", "Gregg Sulkin", "Allegra Acosta"], trailerId: "", watchBefore: [], watchAfter: ["cloak-dagger-temporadas-1-y-2"], postCredits: [], sources: [{ label: "MARVEL TELEVISION", url: "https://www.marvel.com/tv-shows" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "cloak-dagger-temporadas-1-y-2", spoilerFreeSynopsis: "Tandy Bowen y Tyrone Johnson descubren que sus poderes de luz y oscuridad están conectados y los utilizan para proteger Nueva Orleans.", releaseDate: "2018–2019", releaseDateISO: "2018-06-07", runtime: "20 EPISODIOS", certification: "TV-14", status: "ESTRENADO", availability: "DISPONIBILIDAD SEGÚN REGIÓN", directors: ["Gina Prince-Bythewood", "Jennifer Phang", "Jeff Woolnough"], writers: ["Joe Pokaski"], cast: ["Olivia Holt", "Aubrey Joseph", "Gloria Reuben", "Andrea Roth", "J. D. Evermore", "Emma Lahana"], trailerId: "", watchBefore: [], watchAfter: ["runaways-temporadas-1-3"], postCredits: [], sources: [{ label: "MARVEL TELEVISION", url: "https://www.marvel.com/tv-shows" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "daredevil-born-again-temporada-1", spoilerFreeSynopsis: "Matt Murdock intenta defender la justicia desde su bufete mientras Wilson Fisk abandona aparentemente el crimen para perseguir el poder político de Nueva York.",
      releaseDate: "4 MAR 2025", releaseDateISO: "2025-03-04", runtime: "9 EPISODIOS", certification: "TV-MA", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Justin Benson", "Aaron Moorhead", "Michael Cuesta", "Jeffrey Nachmanoff", "David Boyd"], writers: ["Dario Scardapane"], cast: ["Charlie Cox", "Vincent D'Onofrio", "Margarita Levieva", "Deborah Ann Woll", "Elden Henson", "Jon Bernthal"], trailerId: "7xALolZzhSM",
      watchBefore: ["daredevil-temporada-3", "ojo-de-halcon", "echo"], watchAfter: ["daredevil-born-again-temporada-2", "the-punisher-one-last-kill"], postCredits: [{ label: "ESCENA FINAL DEL EPISODIO 9", description: "Fisk impone la ley marcial y persigue a los vigilantes; Matt comienza a reunir aliados para organizar la resistencia." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/daredevil-born-again/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "daredevil-born-again-temporada-2", spoilerFreeSynopsis: "Con Nueva York sometida al régimen de Fisk, Matt Murdock actúa desde las sombras para reconstruir una resistencia y recuperar la ciudad.",
      releaseDate: "MAR 2026", releaseDateISO: "2026-03-24", runtime: "8 EPISODIOS", certification: "TV-MA", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Justin Benson", "Aaron Moorhead"], writers: ["Dario Scardapane"], cast: ["Charlie Cox", "Vincent D'Onofrio", "Deborah Ann Woll", "Krysten Ritter", "Matthew Lillard", "Wilson Bethel"], trailerId: "",
      watchBefore: ["daredevil-born-again-temporada-1"], watchAfter: ["the-punisher-one-last-kill"], postCredits: [],
      sources: [{ label: "MARVEL TELEVISION", url: "https://www.marvel.com/tv-shows" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "the-punisher-one-last-kill", spoilerFreeSynopsis: "Frank Castle regresa en una presentación especial conectada con el nuevo conflicto urbano abierto por el ascenso de Wilson Fisk.",
      releaseDate: "12 MAY 2026", releaseDateISO: "2026-05-12", runtime: "ESPECIAL", certification: "TV-MA", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Reinaldo Marcus Green"], writers: ["Jon Bernthal", "Reinaldo Marcus Green"], cast: ["Jon Bernthal"], trailerId: "",
      watchBefore: ["the-punisher-temporada-2", "daredevil-born-again-temporada-2"], watchAfter: [], postCredits: [],
      sources: [{ label: "CALENDARIO OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows" }], reviewedAt: "30 AGO 2026",
    },
];
