import type { TitleDetails } from "./types";

export const multiverseSagaTitleDetails: TitleDetails[] = [
  {
      titleId: "spider-man-brand-new-day", spoilerFreeSynopsis: "Peter Parker continúa su vida como un Spider-Man anónimo después de que el mundo olvidara su identidad y sus vínculos personales.", releaseDate: "31 JUL 2026", releaseDateISO: "2026-07-31", runtime: "POR CONFIRMAR", certification: "POR CONFIRMAR", status: "ESTRENADO", availability: "CINES", directors: ["Destin Daniel Cretton"], writers: ["Chris McKenna", "Erik Sommers"], cast: ["Tom Holland", "Zendaya", "Jacob Batalon", "Sadie Sink", "Jon Bernthal", "Mark Ruffalo"], trailerId: "tLeBDumanoc", watchBefore: ["spider-man-no-way-home", "daredevil-born-again-temporada-2"], watchAfter: ["avengers-doomsday"], postCredits: [], sources: [{ label: "CALENDARIO OFICIAL MARVEL", url: "https://www.marvel.com/movies" }, { label: "TRÁILER OFICIAL MARVEL", url: "https://www.youtube.com/watch?v=tLeBDumanoc" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "echo", spoilerFreeSynopsis: "Perseguida por las consecuencias de sus actos en Nueva York, Maya López regresa a Oklahoma y debe reconciliarse con su familia, sus raíces choctaw y la influencia de Wilson Fisk.",
      releaseDate: "9 ENE 2024", releaseDateISO: "2024-01-09", runtime: "5 EPISODIOS", certification: "TV-MA", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Sydney Freeland", "Catriona McKenzie"], writers: ["Marion Dayre", "Amy Rardin"], cast: ["Alaqua Cox", "Chaske Spencer", "Tantoo Cardinal", "Devery Jacobs", "Zahn McClarnon", "Vincent D'Onofrio"], trailerId: "AFUKnherhuw",
      watchBefore: ["ojo-de-halcon"], watchAfter: ["daredevil-born-again-temporada-1"], postCredits: [{ label: "ESCENA FINAL", description: "Fisk observa una noticia sobre la falta de candidatos a la alcaldía de Nueva York y considera entrar en la carrera política." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/echo/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "ironheart", spoilerFreeSynopsis: "Riri Williams regresa a Chicago decidida a construir una armadura a su manera, pero sus ambiciones la vinculan con Parker Robbins y un poder de naturaleza mágica.",
      releaseDate: "24 JUN 2025", releaseDateISO: "2025-06-24", runtime: "6 EPISODIOS", certification: "TV-14", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Sam Bailey", "Angela Barnes"], writers: ["Chinaka Hodge"], cast: ["Dominique Thorne", "Anthony Ramos", "Lyric Ross", "Alden Ehrenreich", "Regan Aliyah", "Manny Montana"], trailerId: "WpW36ldAqnM",
      watchBefore: ["black-panther-wakanda-forever"], watchAfter: ["avengers-doomsday"], postCredits: [{ label: "ESCENA FINAL DEL EPISODIO 6", description: "Parker Robbins busca recuperar su poder y conoce a Zelma Stanton, abriendo una nueva vía hacia el mundo mágico." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/ironheart/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "invasion-secreta", spoilerFreeSynopsis: "Nick Fury vuelve a la Tierra al descubrir que una facción rebelde de Skrulls lleva años infiltrándose y pretende desencadenar una guerra entre potencias humanas.",
      releaseDate: "21 JUN 2023", releaseDateISO: "2023-06-21", runtime: "6 EPISODIOS", certification: "TV-14", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Ali Selim"], writers: ["Kyle Bradstreet", "Brian Tucker"], cast: ["Samuel L. Jackson", "Ben Mendelsohn", "Kingsley Ben-Adir", "Emilia Clarke", "Olivia Colman", "Don Cheadle"], trailerId: "Tp_YZNqNBhw",
      watchBefore: ["capitana-marvel", "spider-man-lejos-de-casa"], watchAfter: ["the-marvels"], postCredits: [],
      sources: [{ label: "INFORMACIÓN OFICIAL MARVEL", url: "https://www.marvel.com/articles/tv-shows/secret-invasion-trailer-poster" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "wonder-man", spoilerFreeSynopsis: "El actor Simon Williams intenta conseguir el papel protagonista de una nueva adaptación de Wonder Man y encuentra en Trevor Slattery un mentor tan improbable como experimentado.",
      releaseDate: "2026", releaseDateISO: "2026-01-27", runtime: "8 EPISODIOS", certification: "TV-14", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Destin Daniel Cretton", "Stella Meghie", "James Ponsoldt"], writers: ["Andrew Guest"], cast: ["Yahya Abdul-Mateen II", "Ben Kingsley", "Arian Moayed", "Demetrius Grosse", "Ed Harris", "X Mayo"], trailerId: "",
      watchBefore: ["iron-man-3", "todos-aclaman-al-rey", "shang-chi-y-la-leyenda-de-los-diez-anillos"], watchAfter: [], postCredits: [],
      sources: [{ label: "MARVEL TELEVISION", url: "https://www.marvel.com/tv-shows" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "shang-chi-y-la-leyenda-de-los-diez-anillos", spoilerFreeSynopsis: "Shang-Chi lleva una vida anónima en San Francisco hasta que la organización de los Diez Anillos lo obliga a enfrentarse al pasado familiar del que huyó.",
      releaseDate: "3 SEP 2021", releaseDateISO: "2021-09-03", runtime: "132 MIN", certification: "PG-13", status: "ESTRENADO", availability: "DISNEY+ · DIGITAL · BLU-RAY",
      directors: ["Destin Daniel Cretton"], writers: ["Dave Callaham", "Destin Daniel Cretton", "Andrew Lanham"], cast: ["Simu Liu", "Awkwafina", "Meng'er Zhang", "Fala Chen", "Florian Munteanu", "Tony Leung"], trailerId: "8YjFbMbfXaQ",
      watchBefore: ["iron-man-3"], watchAfter: ["she-hulk-abogada-hulka", "avengers-doomsday"], postCredits: [{ label: "ESCENA INTERMEDIA", description: "Wong, Bruce Banner y Carol Danvers estudian los Diez Anillos y descubren que están emitiendo una señal de origen desconocido." }, { label: "ESCENA FINAL", description: "Xialing toma el control de la organización y reforma los Diez Anillos en lugar de desmantelarlos." }],
      sources: [{ label: "INFORMACIÓN OFICIAL MARVEL", url: "https://www.marvel.com/watch/trailers-and-extras/marvel-studios-shang-chi-and-the-legend-of-the-ten-rings-official-teaser" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "eternals", spoilerFreeSynopsis: "Después de miles de años viviendo ocultos, diez seres inmortales enviados por los Celestiales deben reunirse cuando una nueva Emergencia amenaza la Tierra.",
      releaseDate: "5 NOV 2021", releaseDateISO: "2021-11-05", runtime: "156 MIN", certification: "PG-13", status: "ESTRENADO", availability: "DISNEY+ · DIGITAL · BLU-RAY",
      directors: ["Chloé Zhao"], writers: ["Chloé Zhao", "Patrick Burleigh", "Ryan Firpo", "Kaz Firpo"], cast: ["Gemma Chan", "Richard Madden", "Angelina Jolie", "Kumail Nanjiani", "Salma Hayek", "Brian Tyree Henry"], trailerId: "x_me3xsvDgk",
      watchBefore: ["vengadores-endgame"], watchAfter: ["capitan-america-brave-new-world", "avengers-doomsday"], postCredits: [{ label: "ESCENA INTERMEDIA", description: "Eros, hermano de Thanos, se ofrece a ayudar a localizar a los Eternos capturados por Arishem." }, { label: "ESCENA FINAL", description: "Dane Whitman se dispone a tocar la Espada de Ébano cuando una voz fuera de plano le pregunta si está preparado." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/movies/the-eternals" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "ojo-de-halcon", spoilerFreeSynopsis: "Clint Barton intenta volver con su familia por Navidad, pero una joven arquera llamada Kate Bishop lo arrastra a una conspiración conectada con su pasado como Ronin.",
      releaseDate: "24 NOV 2021", releaseDateISO: "2021-11-24", runtime: "6 EPISODIOS", certification: "TV-14", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Rhys Thomas", "Bert & Bertie"], writers: ["Jonathan Igla"], cast: ["Jeremy Renner", "Hailee Steinfeld", "Tony Dalton", "Alaqua Cox", "Fra Fee", "Florence Pugh"], trailerId: "5VYb3B1ETlk",
      watchBefore: ["vengadores-endgame", "black-widow"], watchAfter: ["echo", "daredevil-born-again-temporada-1"], postCredits: [{ label: "ESCENA FINAL DEL EPISODIO 6", description: "La producción teatral Rogers: The Musical interpreta completa la canción Save the City." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/hawkeye/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "moon-knight", spoilerFreeSynopsis: "Steven Grant sufre apagones y recuerdos de otra vida hasta descubrir que comparte cuerpo con Marc Spector, un mercenario ligado al dios egipcio Khonshu.",
      releaseDate: "30 MAR 2022", releaseDateISO: "2022-03-30", runtime: "6 EPISODIOS", certification: "TV-14", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Mohamed Diab", "Justin Benson", "Aaron Moorhead"], writers: ["Jeremy Slater"], cast: ["Oscar Isaac", "May Calamawy", "Karim El Hakim", "F. Murray Abraham", "Ethan Hawke"], trailerId: "x7Krla_UxRg",
      watchBefore: [], watchAfter: ["werewolf-by-night"], postCredits: [{ label: "ESCENA FINAL DEL EPISODIO 6", description: "Khonshu presenta a Jake Lockley, una tercera identidad que continúa ejecutando su voluntad en secreto." }],
      sources: [{ label: "PERSONAJE OFICIAL MARVEL", url: "https://www.marvel.com/characters/moon-knight-marc-spector/" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "she-hulk-abogada-hulka", spoilerFreeSynopsis: "Jennifer Walters adquiere habilidades sobrehumanas y debe compaginar su nueva identidad pública con una carrera especializada en derecho para superhumanos.",
      releaseDate: "18 AGO 2022", releaseDateISO: "2022-08-18", runtime: "9 EPISODIOS", certification: "TV-14", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Kat Coiro", "Anu Valia"], writers: ["Jessica Gao"], cast: ["Tatiana Maslany", "Ginger Gonzaga", "Jameela Jamil", "Tim Roth", "Mark Ruffalo", "Charlie Cox"], trailerId: "u7JsKhI2An0",
      watchBefore: ["el-increible-hulk", "shang-chi-y-la-leyenda-de-los-diez-anillos"], watchAfter: ["daredevil-born-again-temporada-1"], postCredits: [{ label: "ESCENAS DE EPISODIO", description: "La serie incluye escenas adicionales en varios capítulos, entre ellas la confirmación de que Steve Rogers perdió la virginidad durante su gira de guerra." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/she-hulk-attorney-at-law/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "thor-love-and-thunder", spoilerFreeSynopsis: "Thor busca una nueva dirección para su vida mientras Gorr comienza a asesinar dioses y Jane Foster empuña una versión reconstruida de Mjolnir.",
      releaseDate: "8 JUL 2022", releaseDateISO: "2022-07-08", runtime: "119 MIN", certification: "PG-13", status: "ESTRENADO", availability: "DISNEY+ · DIGITAL · BLU-RAY",
      directors: ["Taika Waititi"], writers: ["Taika Waititi", "Jennifer Kaytin Robinson"], cast: ["Chris Hemsworth", "Natalie Portman", "Christian Bale", "Tessa Thompson", "Taika Waititi", "Russell Crowe"], trailerId: "Go8nTmfrQd8",
      watchBefore: ["thor-ragnarok", "vengadores-endgame"], watchAfter: ["guardianes-de-la-galaxia-especial-felices-fiestas"], postCredits: [{ label: "ESCENA INTERMEDIA", description: "Zeus envía a su hijo Hércules para que obligue a los humanos a volver a temer a los dioses." }, { label: "ESCENA FINAL", description: "Jane llega al Valhalla y es recibida por Heimdall." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/movies/thor-love-and-thunder" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "black-panther-wakanda-forever", spoilerFreeSynopsis: "Wakanda afronta la pérdida de su rey y la presión internacional cuando la aparición de Talokan convierte el vibranium en el centro de un nuevo conflicto.",
      releaseDate: "11 NOV 2022", releaseDateISO: "2022-11-11", runtime: "161 MIN", certification: "PG-13", status: "ESTRENADO", availability: "DISNEY+ · DIGITAL · BLU-RAY",
      directors: ["Ryan Coogler"], writers: ["Ryan Coogler", "Joe Robert Cole"], cast: ["Letitia Wright", "Lupita Nyong'o", "Danai Gurira", "Winston Duke", "Tenoch Huerta Mejía", "Angela Bassett"], trailerId: "_Z3QKkl1WyM",
      watchBefore: ["black-panther", "vengadores-endgame"], watchAfter: ["ironheart", "avengers-doomsday"], postCredits: [{ label: "ESCENA INTERMEDIA", description: "Nakia presenta a Shuri a su hijo Toussaint, cuyo nombre wakandiano es T'Challa." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/movies/black-panther-wakanda-forever" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "guardianes-de-la-galaxia-especial-felices-fiestas", spoilerFreeSynopsis: "Mantis y Drax viajan a la Tierra para encontrar el regalo perfecto que devuelva a Peter Quill el espíritu de la Navidad.",
      releaseDate: "25 NOV 2022", releaseDateISO: "2022-11-25", runtime: "44 MIN", certification: "TV-14", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["James Gunn"], writers: ["James Gunn"], cast: ["Chris Pratt", "Dave Bautista", "Karen Gillan", "Pom Klementieff", "Vin Diesel", "Kevin Bacon"], trailerId: "OYhFFQl4fLs",
      watchBefore: ["guardianes-de-la-galaxia-vol-2", "vengadores-endgame", "thor-love-and-thunder"], watchAfter: ["guardianes-de-la-galaxia-vol-3"], postCredits: [{ label: "ESCENA FINAL", description: "Rocket y Cosmo intentan decorar a Groot; Rocket concluye que necesitarán preparar otro especial." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/the-guardians-of-the-galaxy-holiday-special/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "guardianes-de-la-galaxia-vol-3", spoilerFreeSynopsis: "Cuando Rocket resulta gravemente herido, los Guardianes deben investigar su origen y enfrentarse al Alto Evolucionador para salvar a su amigo.",
      releaseDate: "5 MAY 2023", releaseDateISO: "2023-05-05", runtime: "150 MIN", certification: "PG-13", status: "ESTRENADO", availability: "DISNEY+ · DIGITAL · BLU-RAY",
      directors: ["James Gunn"], writers: ["James Gunn"], cast: ["Chris Pratt", "Zoe Saldaña", "Dave Bautista", "Karen Gillan", "Pom Klementieff", "Will Poulter"], trailerId: "u3V5KDHRQvk",
      watchBefore: ["guardianes-de-la-galaxia-especial-felices-fiestas"], watchAfter: ["avengers-doomsday"], postCredits: [{ label: "ESCENA INTERMEDIA", description: "Rocket lidera una nueva formación de Guardianes junto a Groot, Kraglin, Cosmo, Adam Warlock y Phyla." }, { label: "ESCENA FINAL", description: "Peter se adapta a la vida terrestre con su abuelo y se anuncia que el legendario Star-Lord regresará." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/movies/guardians-of-the-galaxy-volume-3" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "werewolf-by-night", spoilerFreeSynopsis: "Un grupo de cazadores se reúne en Bloodstone Manor para competir por una poderosa reliquia, sin saber que uno de ellos oculta una naturaleza monstruosa.",
      releaseDate: "7 OCT 2022", releaseDateISO: "2022-10-07", runtime: "53 MIN", certification: "TV-14", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Michael Giacchino"], writers: ["Heather Quinn", "Peter Cameron"], cast: ["Gael García Bernal", "Laura Donnelly", "Harriet Sansom Harris", "Kirk R. Thatcher", "Eugenie Bondurant"], trailerId: "bLEFqhS5WmI",
      watchBefore: [], watchAfter: ["moon-knight"], postCredits: [],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/werewolf-by-night/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "falcon-y-el-soldado-de-invierno",
      spoilerFreeSynopsis: "Sam Wilson y Bucky Barnes afrontan el vacío dejado por Steve Rogers mientras un nuevo Capitán América y los Flag Smashers disputan el significado del escudo.",
      releaseDate: "19 MAR 2021", releaseDateISO: "2021-03-19", runtime: "6 EPISODIOS", certification: "TV-14", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Kari Skogland"], writers: ["Malcolm Spellman"], cast: ["Anthony Mackie", "Sebastian Stan", "Daniel Brühl", "Emily VanCamp", "Wyatt Russell", "Erin Kellyman"], trailerId: "IWBsDaFWyTE",
      watchBefore: ["capitan-america-civil-war", "vengadores-endgame"], watchAfter: ["capitan-america-brave-new-world", "thunderbolts"],
      postCredits: [{ label: "ESCENA FINAL DEL EPISODIO 6", description: "Sharon Carter recibe el indulto y recupera su puesto, pero planea vender secretos y tecnología desde dentro del Gobierno." }],
      sources: [{ label: "INFORMACIÓN OFICIAL MARVEL", url: "https://www.marvel.com/articles/tv-shows/falcon-winter-soldier-most-watched-series-premiere-ever-disney-plus" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "ms-marvel",
      spoilerFreeSynopsis: "Kamala Khan, una adolescente de Jersey City fascinada por los Vengadores, encuentra un brazalete familiar que despierta una conexión con su pasado y nuevas habilidades.",
      releaseDate: "8 JUN 2022", releaseDateISO: "2022-06-08", runtime: "6 EPISODIOS", certification: "TV-14", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Adil El Arbi", "Bilall Fallah", "Meera Menon", "Sharmeen Obaid-Chinoy"], writers: ["Bisha K. Ali"], cast: ["Iman Vellani", "Matt Lintz", "Yasmeen Fletcher", "Zenobia Shroff", "Mohan Kapur", "Saagar Shaikh"], trailerId: "m9EX0f6V11Y",
      watchBefore: ["capitana-marvel", "vengadores-endgame"], watchAfter: ["the-marvels"],
      postCredits: [{ label: "ESCENA FINAL DEL EPISODIO 6", description: "El brazalete reacciona y Kamala desaparece; Carol Danvers aparece de forma repentina en su habitación." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/ms-marvel/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "black-widow",
      spoilerFreeSynopsis: "Entre Civil War e Infinity War, Natasha Romanoff se reúne con su antigua familia encubierta para derribar el programa que convirtió a muchas jóvenes en Viudas.",
      releaseDate: "9 JUL 2021", releaseDateISO: "2021-07-09", runtime: "134 MIN", certification: "PG-13", status: "ESTRENADO", availability: "DISNEY+ · DIGITAL · BLU-RAY",
      directors: ["Cate Shortland"], writers: ["Eric Pearson"], cast: ["Scarlett Johansson", "Florence Pugh", "David Harbour", "Rachel Weisz", "O-T Fagbenle", "Ray Winstone"], trailerId: "RxAtuMu_ph4",
      watchBefore: ["capitan-america-civil-war"], watchAfter: ["vengadores-infinity-war", "ojo-de-halcon", "thunderbolts"],
      postCredits: [{ label: "ESCENA FINAL", description: "Después de Endgame, Valentina Allegra de Fontaine muestra a Yelena una foto de Clint Barton y lo señala como responsable de la muerte de Natasha." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/movies/black-widow" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "wandavision",
      spoilerFreeSynopsis: "Wanda Maximoff y Vision viven una existencia de comedia televisiva en Westview, pero la realidad que los rodea empieza a revelar grietas y una amenaza exterior.",
      releaseDate: "15 ENE 2021", releaseDateISO: "2021-01-15", runtime: "9 EPISODIOS", certification: "TV-14", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Matt Shakman"], writers: ["Jac Schaeffer"], cast: ["Elizabeth Olsen", "Paul Bettany", "Kathryn Hahn", "Teyonah Parris", "Kat Dennings", "Randall Park"], trailerId: "sj9J2ecsSpo",
      watchBefore: ["vengadores-la-era-de-ultron", "capitan-america-civil-war", "vengadores-endgame"], watchAfter: ["doctor-strange-en-el-multiverso-de-la-locura", "agatha-quien-si-no"],
      postCredits: [{ label: "ESCENA INTERMEDIA", description: "Monica Rambeau recibe la visita de una Skrull que la convoca en nombre de un amigo de su madre." }, { label: "ESCENA FINAL", description: "Wanda estudia el Darkhold en forma astral y oye a sus hijos pedir ayuda." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/wandavision/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "ant-man-y-la-avispa-quantumania",
      spoilerFreeSynopsis: "La familia de Scott Lang queda atrapada en el Reino Cuántico, donde descubre una civilización sometida y al conquistador que domina ese mundo oculto.",
      releaseDate: "17 FEB 2023", releaseDateISO: "2023-02-17", runtime: "125 MIN", certification: "PG-13", status: "ESTRENADO", availability: "DISNEY+ · DIGITAL · BLU-RAY",
      directors: ["Peyton Reed"], writers: ["Jeff Loveness"], cast: ["Paul Rudd", "Evangeline Lilly", "Jonathan Majors", "Kathryn Newton", "Michelle Pfeiffer", "Michael Douglas"], trailerId: "ZlNFpri-Y40",
      watchBefore: ["ant-man", "ant-man-y-la-avispa", "loki-temporadas-1-y-2"], watchAfter: ["avengers-doomsday"],
      postCredits: [{ label: "ESCENA INTERMEDIA", description: "Un consejo formado por numerosas variantes de Kang se reúne tras la muerte del Conquistador." }, { label: "ESCENA FINAL", description: "Loki y Mobius observan en el siglo XIX una presentación de Victor Timely, otra variante de Kang." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/antman" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "the-marvels",
      spoilerFreeSynopsis: "Los poderes de Carol Danvers, Monica Rambeau y Kamala Khan quedan entrelazados, obligándolas a coordinarse mientras una revolucionaria Kree desestabiliza la red de saltos espaciales.",
      releaseDate: "10 NOV 2023", releaseDateISO: "2023-11-10", runtime: "105 MIN", certification: "PG-13", status: "ESTRENADO", availability: "DISNEY+ · DIGITAL · BLU-RAY",
      directors: ["Nia DaCosta"], writers: ["Megan McDonnell", "Nia DaCosta", "Elissa Karasik", "Zeb Wells"], cast: ["Brie Larson", "Teyonah Parris", "Iman Vellani", "Zawe Ashton", "Samuel L. Jackson", "Park Seo-joon"], trailerId: "wS_qbDztgVY",
      watchBefore: ["capitana-marvel", "wandavision", "ms-marvel"], watchAfter: ["avengers-doomsday"],
      postCredits: [{ label: "ESCENA INTERMEDIA", description: "Monica despierta en otra realidad, donde encuentra a una variante de su madre y al mutante Hank McCoy." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/movies/the-marvels" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "agatha-quien-si-no",
      spoilerFreeSynopsis: "Sin poderes y atrapada tras los sucesos de Westview, Agatha Harkness reúne un aquelarre para recorrer la legendaria Senda de las Brujas.",
      releaseDate: "18 SEP 2024", releaseDateISO: "2024-09-18", runtime: "9 EPISODIOS", certification: "TV-14", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Jac Schaeffer", "Rachel Goldberg", "Gandja Monteiro"], writers: ["Jac Schaeffer"], cast: ["Kathryn Hahn", "Joe Locke", "Sasheer Zamata", "Ali Ahn", "Patti LuPone", "Aubrey Plaza"], trailerId: "R9pXbNz6Vbw",
      watchBefore: ["wandavision", "doctor-strange-en-el-multiverso-de-la-locura"], watchAfter: ["avengers-doomsday"],
      postCredits: [],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/agatha-all-along/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "capitan-america-brave-new-world",
      spoilerFreeSynopsis: "Sam Wilson queda atrapado en un incidente internacional tras reunirse con el presidente Thaddeus Ross y debe descubrir quién dirige la conspiración.",
      releaseDate: "14 FEB 2025", releaseDateISO: "2025-02-14", runtime: "118 MIN", certification: "PG-13", status: "ESTRENADO", availability: "DISNEY+ · DIGITAL · BLU-RAY",
      directors: ["Julius Onah"], writers: ["Rob Edwards", "Malcolm Spellman", "Dalan Musson", "Julius Onah", "Peter Glanz"], cast: ["Anthony Mackie", "Danny Ramirez", "Harrison Ford", "Tim Blake Nelson", "Carl Lumbly", "Giancarlo Esposito"], trailerId: "1pHDWnXmK7Y",
      watchBefore: ["el-increible-hulk", "falcon-y-el-soldado-de-invierno", "eternals"], watchAfter: ["thunderbolts", "avengers-doomsday"],
      postCredits: [{ label: "ESCENA FINAL", description: "Samuel Sterns advierte a Sam de que otros mundos se aproximan, una amenaza vinculada al conflicto multiversal." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/movies/captain-america-brave-new-world" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "thunderbolts",
      spoilerFreeSynopsis: "Yelena Belova y varios operativos descartados caen en una trampa de Valentina Allegra de Fontaine y deben decidir si pueden convertirse en un verdadero equipo.",
      releaseDate: "2 MAY 2025", releaseDateISO: "2025-05-02", runtime: "127 MIN", certification: "PG-13", status: "ESTRENADO", availability: "DISNEY+ · DIGITAL · BLU-RAY",
      directors: ["Jake Schreier"], writers: ["Eric Pearson", "Joanna Calo"], cast: ["Florence Pugh", "Sebastian Stan", "Wyatt Russell", "Lewis Pullman", "David Harbour", "Julia Louis-Dreyfus"], trailerId: "bqnRzjPfb5A",
      watchBefore: ["black-widow", "falcon-y-el-soldado-de-invierno", "capitan-america-brave-new-world"], watchAfter: ["avengers-doomsday"],
      postCredits: [{ label: "ESCENA FINAL", description: "Los Nuevos Vengadores detectan una nave marcada con el emblema de los Cuatro Fantásticos entrando en su universo." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/movies/thunderbolts" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "loki-temporadas-1-y-2",
      spoilerFreeSynopsis: "Una variante de Loki queda bajo custodia de la TVA y descubre que el orden temporal que parecía absoluto esconde una verdad mucho más peligrosa.",
      releaseDate: "2021–2023", releaseDateISO: "2021-06-09", runtime: "12 EPISODIOS", certification: "TV-14", status: "ESTRENADO", availability: "DISNEY+",
      directors: ["Kate Herron", "Justin Benson", "Aaron Moorhead", "Dan DeLeeuw", "Kasra Farahani"], writers: ["Michael Waldron", "Eric Martin"], cast: ["Tom Hiddleston", "Sophia Di Martino", "Owen Wilson", "Gugu Mbatha-Raw", "Wunmi Mosaku", "Ke Huy Quan"], trailerId: "dug56u8NN7g",
      watchBefore: ["los-vengadores", "vengadores-endgame"], watchAfter: ["deadpool-y-lobezno", "avengers-doomsday"], postCredits: [],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/tv-shows/loki/1" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "spider-man-no-way-home",
      spoilerFreeSynopsis: "Con su identidad expuesta, Peter Parker pide ayuda a Doctor Strange y desencadena una crisis que rompe las fronteras de su mundo.",
      releaseDate: "17 DIC 2021", releaseDateISO: "2021-12-17", runtime: "148 MIN", certification: "PG-13", status: "ESTRENADO", availability: "DISPONIBILIDAD SEGÚN REGIÓN",
      directors: ["Jon Watts"], writers: ["Chris McKenna", "Erik Sommers"], cast: ["Tom Holland", "Zendaya", "Benedict Cumberbatch", "Jacob Batalon", "Willem Dafoe", "Alfred Molina"], trailerId: "JfVOs4VSpmA",
      watchBefore: ["spider-man-lejos-de-casa", "loki-temporadas-1-y-2"], watchAfter: ["doctor-strange-en-el-multiverso-de-la-locura", "spider-man-brand-new-day"],
      postCredits: [{ label: "ESCENA INTERMEDIA", description: "Un visitante de otra realidad deja tras de sí una pequeña parte de un simbionte antes de regresar a su universo." }],
      sources: [{ label: "MARVEL · PELÍCULAS", url: "https://www.marvel.com/movies/spider-man-no-way-home" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "doctor-strange-en-el-multiverso-de-la-locura",
      spoilerFreeSynopsis: "Doctor Strange protege a una joven capaz de viajar entre universos mientras una amenaza vinculada al Darkhold persigue su poder.",
      releaseDate: "6 MAY 2022", releaseDateISO: "2022-05-06", runtime: "126 MIN", certification: "PG-13", status: "ESTRENADO", availability: "DISNEY+ · DIGITAL · BLU-RAY",
      directors: ["Sam Raimi"], writers: ["Michael Waldron"], cast: ["Benedict Cumberbatch", "Elizabeth Olsen", "Benedict Wong", "Xochitl Gomez", "Rachel McAdams", "Chiwetel Ejiofor"], trailerId: "aWzlQ2N6qqg",
      watchBefore: ["doctor-strange", "wandavision", "spider-man-no-way-home"], watchAfter: ["agatha-quien-si-no", "avengers-doomsday"],
      postCredits: [{ label: "ESCENA INTERMEDIA", description: "Clea recluta a Strange para reparar una incursión y abre un portal hacia la Dimensión Oscura." }, { label: "ESCENA FINAL", description: "Pizza Poppa deja de golpearse cuando termina el hechizo y celebra que la espera ha terminado." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/movies/doctor-strange-in-the-multiverse-of-madness" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "deadpool-y-lobezno",
      spoilerFreeSynopsis: "Wade Wilson abandona su retiro cuando la TVA amenaza la supervivencia de su universo y necesita convencer a un Wolverine reticente para ayudarlo.",
      releaseDate: "26 JUL 2024", releaseDateISO: "2024-07-26", runtime: "128 MIN", certification: "R", status: "ESTRENADO", availability: "DISNEY+ · DIGITAL · BLU-RAY",
      directors: ["Shawn Levy"], writers: ["Ryan Reynolds", "Rhett Reese", "Paul Wernick", "Zeb Wells", "Shawn Levy"], cast: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin", "Matthew Macfadyen", "Morena Baccarin", "Rob Delaney"], trailerId: "73_1biulkYk",
      watchBefore: ["loki-temporadas-1-y-2"], watchAfter: ["avengers-doomsday"],
      postCredits: [{ label: "ESCENA FINAL", description: "Una grabación de la TVA demuestra qué dijo realmente Johnny Storm antes de su enfrentamiento con Cassandra Nova." }],
      sources: [{ label: "ESTRENO OFICIAL MARVEL", url: "https://www.marvel.com/deadpool-and-wolverine-live-red-carpet-premiere" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "los-cuatro-fantasticos-primeros-pasos",
      spoilerFreeSynopsis: "En una Tierra retrofuturista, la Primera Familia debe proteger su mundo cuando la llegada de Silver Surfer anuncia una amenaza cósmica imposible.",
      releaseDate: "25 JUL 2025", releaseDateISO: "2025-07-25", runtime: "115 MIN", certification: "PG-13", status: "ESTRENADO", availability: "DISNEY+ · DIGITAL · BLU-RAY",
      directors: ["Matt Shakman"], writers: ["Josh Friedman", "Eric Pearson", "Jeff Kaplan", "Ian Springer"], cast: ["Pedro Pascal", "Vanessa Kirby", "Joseph Quinn", "Ebon Moss-Bachrach", "Ralph Ineson", "Julia Garner"], trailerId: "pAsmrKyMqaA",
      watchBefore: [], watchAfter: ["avengers-doomsday"],
      postCredits: [{ label: "ESCENA INTERMEDIA", description: "Sue encuentra a una figura misteriosa junto a Franklin, anticipando la llegada de Victor von Doom." }, { label: "ESCENA FINAL", description: "Un programa animado dentro de Tierra-828 recupera una versión clásica de la Primera Familia." }],
      sources: [{ label: "FICHA OFICIAL MARVEL", url: "https://www.marvel.com/movies/fantastic-four" }, { label: "CONEXIÓN CON DOOMSDAY", url: "https://www.marvel.com/articles/movies/fantastic-four-first-steps-avengers-doomsday-kevin-feige" }], reviewedAt: "30 AGO 2026",
    },
];
