import type { TitleDetails } from "./types";

export const oneShotsTitleDetails: TitleDetails[] = [
  {
      titleId: "el-consultor", spoilerFreeSynopsis: "Coulson y Sitwell diseñan una maniobra para impedir que el Consejo incorpore a Emil Blonsky a la Iniciativa Vengadores.", releaseDate: "13 SEP 2011", releaseDateISO: "2011-09-13", runtime: "4 MIN", certification: "TV-PG", status: "ESTRENADO", availability: "DISNEY+ · BLU-RAY", directors: ["Leythum"], writers: ["Eric Pearson"], cast: ["Clark Gregg", "Maximiliano Hernández", "Robert Downey Jr.", "William Hurt"], trailerId: "", watchBefore: ["el-increible-hulk", "iron-man-2"], watchAfter: ["los-vengadores"], postCredits: [], sources: [{ label: "MARVEL STUDIOS ONE-SHOTS", url: "https://www.marvel.com/articles/movies/marvel-one-shot-all-hail-the-king-disney-plus" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "algo-divertido-ocurrio-de-camino-al-martillo-de-thor", spoilerFreeSynopsis: "Durante una parada de camino a Nuevo México, Phil Coulson demuestra por qué S.H.I.E.L.D. confía en él para misiones de campo.", releaseDate: "25 OCT 2011", releaseDateISO: "2011-10-25", runtime: "4 MIN", certification: "TV-PG", status: "ESTRENADO", availability: "DISNEY+ · BLU-RAY", directors: ["Leythum"], writers: ["Eric Pearson"], cast: ["Clark Gregg", "Jessica Manuel", "Jeff Prewett"], trailerId: "", watchBefore: ["iron-man-2"], watchAfter: ["thor"], postCredits: [], sources: [{ label: "MARVEL STUDIOS ONE-SHOTS", url: "https://www.marvel.com/articles/movies/marvel-one-shot-all-hail-the-king-disney-plus" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "articulo-47", spoilerFreeSynopsis: "Una pareja encuentra un arma Chitauri después de la batalla de Nueva York y la utiliza para iniciar una cadena de atracos que atrae a S.H.I.E.L.D.", releaseDate: "25 SEP 2012", releaseDateISO: "2012-09-25", runtime: "12 MIN", certification: "TV-PG", status: "ESTRENADO", availability: "DISNEY+ · BLU-RAY", directors: ["Louis D'Esposito"], writers: ["Eric Pearson"], cast: ["Lizzy Caplan", "Jesse Bradford", "Maximiliano Hernández", "Titus Welliver"], trailerId: "", watchBefore: ["los-vengadores"], watchAfter: ["agents-of-s-h-i-e-l-d-temporada-1"], postCredits: [], sources: [{ label: "MARVEL STUDIOS ONE-SHOTS", url: "https://www.marvel.com/articles/movies/marvel-one-shot-all-hail-the-king-disney-plus" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "agent-carter", spoilerFreeSynopsis: "Peggy Carter acepta una misión que sus compañeros rechazan y demuestra que está preparada para dirigir una nueva etapa del espionaje aliado.", releaseDate: "3 SEP 2013", releaseDateISO: "2013-09-03", runtime: "15 MIN", certification: "TV-PG", status: "ESTRENADO", availability: "DISNEY+ · BLU-RAY", directors: ["Louis D'Esposito"], writers: ["Eric Pearson"], cast: ["Hayley Atwell", "Bradley Whitford", "Dominic Cooper", "Neal McDonough", "Chris Evans"], trailerId: "", watchBefore: ["capitan-america-el-primer-vengador"], watchAfter: ["agent-carter-temporada-1"], postCredits: [], sources: [{ label: "MARVEL STUDIOS ONE-SHOTS", url: "https://www.marvel.com/articles/movies/marvel-one-shot-all-hail-the-king-disney-plus" }], reviewedAt: "30 AGO 2026",
    },
  {
      titleId: "todos-aclaman-al-rey", spoilerFreeSynopsis: "En prisión, Trevor Slattery concede una entrevista sobre su etapa como falso Mandarín sin comprender que los Diez Anillos reales siguen observándolo.", releaseDate: "25 FEB 2014", releaseDateISO: "2014-02-25", runtime: "14 MIN", certification: "TV-PG", status: "ESTRENADO", availability: "DISNEY+ · BLU-RAY", directors: ["Drew Pearce"], writers: ["Drew Pearce"], cast: ["Ben Kingsley", "Scoot McNairy", "Lester Speight", "Sam Rockwell"], trailerId: "", watchBefore: ["iron-man-3"], watchAfter: ["shang-chi-y-la-leyenda-de-los-diez-anillos"], postCredits: [], sources: [{ label: "INFORMACIÓN OFICIAL MARVEL", url: "https://www.marvel.com/articles/movies/marvel-one-shot-all-hail-the-king-disney-plus" }], reviewedAt: "30 AGO 2026",
    },
];
